name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        container: ["node:8", "node:10", "node:12", "node:14", "node:16"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Unit tests
        run: npm run test
